In [2]:
from sklearn.datasets import load_digits
ld=load_digits()
dir(ld)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [9]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
scores_lr=[]
scores_svc=[]
scores_rf=[]
for train_index,test_index in folds.split(ld.data,ld.target):
    x_train,x_test,y_train,y_test=ld.data[train_index],ld.data[test_index],ld.target[train_index],ld.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))
print(scores_lr)
print(scores_rf)
print(scores_svc)

c:\Users\sumit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\sumit\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]
[0.9398998330550918, 0.9549248747913188, 0.9365609348914858]
[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]


In [24]:
from sklearn.model_selection import cross_val_score
scr_lg=cross_val_score(LogisticRegression(solver='liblinear',multi_class='auto'),ld.data,ld.target,cv=5)
print(scr_lg)
print(np.average(scr_lg))

[0.92222222 0.88333333 0.95264624 0.95821727 0.89415042]
0.9221138966264315


In [25]:
scr_svc=cross_val_score(SVC(gamma='scale'),ld.data,ld.target,cv=5)
print(scr_svc)
print(np.average(scr_svc))

[0.96111111 0.94444444 0.98328691 0.98885794 0.93871866]
0.9632838130609718


In [33]:
scr_rf=cross_val_score(RandomForestClassifier(n_estimators=40),ld.data,ld.target,cv=5)
print(scr_rf)
print(np.average(scr_rf))

[0.92222222 0.92777778 0.94986072 0.9637883  0.92479109]
0.9376880222841226
